language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API=26
  - ANDROID_BUILD_TOOLS=28.0.3
  - ADB_INSTALL_TIMEOUT=5
  - UPLOADTOOL_SUFFIX=android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra
  - addon-google_apis-google-27
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
script:
- export STAGE=script
- "./travis.sh"
before_install:
- export STAGE=before_install
- "./travis.sh"
after_success:
- export STAGE=after_success
- "./travis.sh"

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
